[project]
name = "sqlflask"
version = "0.1.0"
description = "A minimal Flask + SQLite + HTMX project"
dependencies = [
  "flask",
  "gunicorn",
  "python-dotenv>=1.1.0",
  "sentry-sdk[flask]>=2.28.0",
  "sqlite-utils",
]
